### ISSUE TITLE
Script does not work if dataset has JPEG without matching annotations

### ISSUE THREAD

**Issue by cabirdme** [aalborov/cut_dataset#1]
I have downloaded the Pascal VOC (2012 I believe) dataset.  This script for cutting a subset of images did not work out of box for me.

I came to figure out that this dataset contains a 2008_000001.jpg file but does not contain a matching 2008_000001.xml annotation file.  In this case, the script returns unsuccessfully:

Traceback (most recent call last):
  File "/mnt/c/Users/cabird/Downloads/VOC/cut_dataset.py", line 158, in <module>
    archive(new_file_names, args.output_archive_dir, output_archive_name, output_folder_dir, rel_path_finder)
  File "/mnt/c/Users/cabird/Downloads/VOC/cut_dataset.py", line 134, in archive
    tar.add(file_name, arcname=relative_path)
  File "/usr/lib/python3.6/tarfile.py", line 1934, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "/usr/lib/python3.6/tarfile.py", line 1803, in gettarinfo
    statres = os.lstat(name)
FileNotFoundError: [Errno 2] No such file or directory: './subsets/temp/VOCdevkit/VOC2012/Annotations/2008_000001.xml'

Maybe I misunderstand, but my workaround for your consideration was inside of cut_voc to check for location of a matching annotation file before appending the image to the names and files_directories lists.

**Comment by aalborov** [comment]
Thank you for the comment, @cabirdme! You are very right. Fixed.
